### ISSUE TITLE
Cannot find module "./example.har"

### ISSUE THREAD

**Issue by dstampher** [Tapico/tapico-msw-webarchive#15]
`import * as traffic from './example.har'`

This line from the example is producing the following error in VS Code:

`Cannot find module ./example.har or its corresponding type definitions.`

It seems that a dependency is not mentioned in the docs for this repo, therefore, I am unable to use it.  I have a file called example.har that is the same directory as the file that is importing it.  The HAR file was generated via Chrome Developer Tools.

Please help by informing me how to import the HAR file.

**Comment by weyert** [comment]
Hmm, thank you for your report. I will have a look.

**Comment by dstampher** [comment]
@weyert Thank you for the response.  I have generated the file (after making some requests to example.com, with Chrome Dev Tools open and the Network tab active and recording).

I was thinking that perhaps I need to install the @types/har-format package?  I also changed the extension to .json, and tried to import that instead.  Typescript informed me that I should enable "resolveJsonModule", so I did that in my tsconfig, but the error remains in VSCode.

**Comment by dstampher** [comment]
I created a new node project, and changed the HAR file extension to json, in addition to enabling the "resolveJsonModule" tsconfig option.  The error went away, and I am getting the expected responses when sending requests to the endpoints listed in the HAR file.  So, everything seems to be working now.

**Comment by weyert** [comment]
Glad it were able to get it working. I am not sure how to improve the experience. 

I thought `declare module '*.har'` would do the trick bit clearly doesn't.
