### ISSUE TITLE
MSW 2.0 Support

### ISSUE THREAD

**Issue by ctuckz** [Tapico/tapico-msw-webarchive#18]
We're adopting MSW and would love to use this library to improve the onboarding process by autogenerating mocks, and as a way to keep mocks in sync with real API implementations. Unfortunately, this project isn't compatible with MSW 2.0. For example, there are [references](https://github.com/Tapico/tapico-msw-webarchive/blob/main/src/serverHandler.ts#L75) to `rest`, which has been removed, and the [response resolver](https://github.com/Tapico/tapico-msw-webarchive/blob/main/src/serverHandler.ts#L88) uses the 1.0 style of intercepting requests.

Are there any plans to support MSW 2.0 in a future version?

**Comment by tapico-weyert** [comment]
Thank you!  We are planning to upgrade to MSW v2 in the coming weeks :)
We are happy to accept a PR, though

**Comment by ctuckz** [comment]
Great to hear! We'd like to start using it a little sooner, so I'll take a stab at the upgrade

**Comment by tapico-weyert** [comment]
@ctuckz I had some issues with publishing the package but it should work now

**Comment by ctuckz** [comment]
Awesome, thanks for getting it released! Looking forward to trying the new version out at work today

**Comment by tapico-weyert** [comment]
Sorry that it took so long. I don't publish enough packages to the npm registry to understand its cryptic error messages 🙈
But it should sorted so should be easy to publish now. Also all up to scratch with our company policies 😎🚀
