### ISSUE TITLE
Add a configuration option to control mock delay behavior

### ISSUE THREAD

**Issue by ctuckz** [Tapico/tapico-msw-webarchive#51]
Currently, mock responses will be delayed when the `time` property in a HAR is set. This can be useful to simulate realistic API latency. We mainly use this library for automated tests however, and these delays could add a significant amount of time to the test run. I'd like to propose adding an option to control how responses are delayed:

**responseDelay**: real | none
Real: Default value. Responses will be delayed based on the `time` property in the HAR, if set.
None: Responses will not be delayed

This option could easily be a boolean but I was thinking that making it a string would help with backwards compatibility if there ever needs to be additional options ([implicit delay](https://mswjs.io/docs/api/delay/#implicit-delay) for example). We'd only use `none` at the moment, however. Also I'm not married to the names in here if you'd prefer calling it something else

Curious what you think! Happy to submit a PR with the change if it sounds ok

**Comment by tapico-weyert** [comment]
Sorry, for the late response! I think it's a great idea 🤗

**Comment by tapico-weyert** [comment]
Don't know if we also want to accept a function that would allow to add a random delay on top of what is defined in the `time`-property? E.g. `function (timeDelay: number) { return timeDelay * 2 }`

**Comment by ctuckz** [comment]
Sorry for my late reply!

That's an interesting idea, are you thinking that the function could replace the `real`/`none` options? Or would it be a third option in addition to the other 2? Using a function is generic enough that you could just have it always return 0 to never sleep and if someone needs to do something fancy, it'd also support that. But at the same time, it might be easier to just set responseDelay to an explicit setting if you don't need the advanced functionality

Maybe the function could also take the request URL as an additional parameter in case someone wants to customize the behavior per route? Or do you think that's too much

**Comment by weyert** [comment]
Yeah, think that would be really cool. Maybe could pass it like some sort of `context` containing the requestInfo (e.g. path, method, etc). Only not sure if we only want to make it a function and then have a default implementation. What would you prefer?

**Comment by ctuckz** [comment]
Hmm might be easier to understand how to use it if there's non-function options, especially since I bet those would be the more common choices. What do you think about:
`responseDelay: 'real' | 'none' | (context, timeDelay) => int`

**Comment by weyert** [comment]
Sounds great!
