### ISSUE TITLE
Search queries not taken into account when defining request handlers

### ISSUE THREAD

**Issue by hugosoares** [Tapico/tapico-msw-webarchive#82]
https://github.com/Tapico/tapico-msw-webarchive/blame/4a77d804d068ff9fc1a6575c84b087b37d8087d7/src/serverHandler.ts#L100

Then above line of code does not make much sense since it completly ignores the search query making every single response the same even if the har file contains multiple different responses for every search query.

Example:
https://myjira.atlassian.net/rest/api/3/project/10147/version?startAt=0&maxResults=50&orderBy=releaseDate&status=unreleased
https://myjira.atlassian.net/rest/api/3/project/10147/version?startAt=0&maxResults=50&orderBy=releaseDate&status=released

AS IS
These two requests will be handled the same way providing the same result,
Expectation
An individual response should be given for each request

**Comment by weyert** [comment]
Think this should be covered in the `@mwsjs/source`-package.
